# basicExample fish shell completion
# Generated by picocli version %1$s: https://picocli.info/
# Install by saving to ~/.config/fish/completions/basicExample.fish, or run:
#   basicExample generate-completion --shell=fish | source
complete -c 'basicExample' -e
complete -c 'basicExample' -s 'u' -l 'timeUnit' -x -a 'NANOSECONDS MICROSECONDS MILLISECONDS SECONDS MINUTES HOURS DAYS'
complete -c 'basicExample' -s 't' -l 'timeout' -r
