# picocompletion-demo fish shell completion
# Generated by picocli version %1$s: https://picocli.info/
# Install by saving to ~/.config/fish/completions/picocompletion-demo.fish, or run:
#   picocompletion-demo generate-completion --shell=fish | source
complete -c 'picocompletion-demo' -e
complete -c 'picocompletion-demo' -n 'not __fish_seen_subcommand_from sub1 sub1-alias sub2 sub2-alias' -s 'V' -l 'version'
complete -c 'picocompletion-demo' -n 'not __fish_seen_subcommand_from sub1 sub1-alias sub2 sub2-alias' -s 'h' -l 'help'
complete -c 'picocompletion-demo' -n 'not __fish_seen_subcommand_from sub1 sub1-alias sub2 sub2-alias' -f -a 'sub1 sub1-alias' -d 'First level subcommand 1'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub1 sub1-alias' -l 'num' -r -d 'a number'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub1 sub1-alias' -l 'str' -r -d 'a String'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub1 sub1-alias' -l 'candidates' -x -a 'aaa bbb ccc' -d 'with candidates'
complete -c 'picocompletion-demo' -n 'not __fish_seen_subcommand_from sub1 sub1-alias sub2 sub2-alias' -f -a 'sub2 sub2-alias' -d 'First level subcommand 2'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -l 'num2' -r -d 'another number'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -l 'directory' -s 'd' -r -d 'a directory'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -l 'thread-state' -x -a 'NEW RUNNABLE BLOCKED WAITING TIMED_WAITING TERMINATED'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -l '<invalid-name>' -r
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -f -a 'Aaa Bbb Ccc'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -f -a 'subsub1 sub2child1-alias' -d 'Second level sub-subcommand 1'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n '__fish_seen_subcommand_from subsub1 sub2child1-alias' -s 'h' -l 'host' -x -a '(__fish_print_hostnames)' -d 'a host'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -f -a 'subsub2 sub2child2-alias' -d 'Second level sub-subcommand 2'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n '__fish_seen_subcommand_from subsub2 sub2child2-alias' -s 'u' -l 'timeUnit' -x -a 'NANOSECONDS MICROSECONDS MILLISECONDS SECONDS MINUTES HOURS DAYS'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n '__fish_seen_subcommand_from subsub2 sub2child2-alias' -s 't' -l 'timeout' -r
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n '__fish_seen_subcommand_from subsub2 sub2child2-alias' -f -a 'aaa bbb ccc' -d 'with candidates'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n 'not __fish_seen_subcommand_from subsub1 sub2child1-alias subsub2 sub2child2-alias subsub3 sub2child3-alias' -f -a 'subsub3 sub2child3-alias' -d 'Second level sub-subcommand 3'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n '__fish_seen_subcommand_from subsub3 sub2child3-alias' -f -a 'aaa bbb ccc'
complete -c 'picocompletion-demo' -n '__fish_seen_subcommand_from sub2 sub2-alias' -n '__fish_seen_subcommand_from subsub3 sub2child3-alias' -f -a '(__fish_print_hostnames)'
