plugins {
    id 'java'
}

group = 'info.picocli'
description = 'Picocli JSON Spec - Build picocli CommandSpec models from a lightweight DSL or JSON, export any CommandSpec to JSON, and merge externally-defined command specs into a host CLI.'
version = "$projectVersion"
ext.moduleName = 'info.picocli.jsonspec'

java {
    if (!JavaVersion.current().isJava9Compatible()) {
        sourceCompatibility = JavaVersion.VERSION_1_6
        targetCompatibility = JavaVersion.VERSION_1_6
    } else { // from Java 9 and up
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

dependencies {
    api rootProject
}

jar {
    manifest {
        attributes 'Specification-Title'   : 'Picocli JSON Spec',
                   'Specification-Vendor'  : 'Remko Popma',
                   'Specification-Version' : archiveVersion.get(),
                   'Implementation-Title'  : 'Picocli JSON Spec',
                   'Implementation-Vendor' : 'Remko Popma',
                   'Implementation-Version': archiveVersion.get()
    }
}

ext {
    PUBLISH_GROUP_ID = group
    PUBLISH_ARTIFACT_ID = project.name
    PUBLISH_VERSION = "$projectVersion"
}
apply from: "${rootProject.projectDir}/gradle/publish-mavencentral.gradle"
